import type { Metadata, Viewport } from "next";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { cn } from "@/lib/utils";
import { fontSirwan } from "@/public/fonts";
import { Toaster } from "sonner";

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body className={cn(`${fontSirwan.variable}  font-medium font-sirwan`)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          {children}
          <Toaster
            dir="rtl"
            toastOptions={{
              className: `${fontSirwan.variable}  font-medium font-sirwan`,
            }}
            richColors
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
export async function generateMetadata(): Promise<Metadata> {
  return {
    title: {
      default: "Khoshnaw Group",
      template: "%s - Khoshnaw Group",
    },
    description: "Generated by Gulle Software",
  };
}

export const viewport: Viewport = {
  userScalable: false,
  maximumScale: 1,
  minimumScale: 1,
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  height: "device-height",
  interactiveWidget: "resizes-content",
};
